# Generated by Django 3.1.6 on 2021-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_free',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
