# Generated by Django 3.1.6 on 2021-04-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_entry_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='entry_free',
            new_name='entry_fee',
        ),
    ]
