# Generated by Django 3.1.6 on 2021-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='membership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
