# Generated by Django 3.1.6 on 2021-03-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_stripecustomer_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='membership',
        ),
    ]
