# Generated by Django 3.1.6 on 2021-03-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210320_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='second_image',
        ),
    ]
